### ISSUE TITLE
[bed_read] Parse error reading SNP.tsv

### ISSUE THREAD

**Issue by DeMagicscience** [eafyounian/Segmentum#3] opened 2024-03-27 02:49 UTC
Thank you for developing Segmentum.
I encountered a problem in preparing BAF input. The error message in log file is:
Pre-filtering variants with less than 4 alt reads...
Ignoring reads with MAPQ below 20...
[bed_read] Parse error reading SNP.tsv at line 1
samtools mpileup: Could not read file "SNP.tsv": Success

I guess the reason may be because samtools is not installed, as you said "Segmentum requires [Samtools] to be installed."
if I install samtools, how can I integrate (or link) it to Segmentum?
Thank you for your time!

**Comment by eafyounian** [comment] 2024-03-27 06:41
Hello, thank you for your message and using Segmentum.
 
If the issue is due to `samtools` not being installed, then installing it should be enough. As long as it is in the `PATH`, Python will find it. Please check if installing `samtools` solves the issue, if not please let me know and we try to figure it out.

- To check if `samtools` is installed, one can use `which samtools` or `command -v samtools`.

**Comment by DeMagicscience** [comment] 2024-03-27 07:11
> Hello, thank you for your message and using Segmentum.
> 
> If the issue is due to `samtools` not being installed, then installing it should be enough. As long as it is in the `PATH`, Python will find it. Please check if installing `samtools` solves the issue, if not please let me know and we try to figure it out.
> 
> * To check if `samtools` is installed, one can use `which samtools` or `command -v samtools`.

Thank you for your reply.
When I input "which samtools", the output is "~/miniconda3/bin/samtools". So, it seems samtools has been already installed.
I cannot download the example file from this link (http://compbio.uta.fi/segmentum/sample_files.tar.gz). In addtition, my reference is hg38. So, I prepared the tumor_sample_SNP.tsv, which I added in the attachment.
[tumor_sample_SNP.zip](https://github.com/eafyounian/Segmentum/files/14769319/tumor_sample_SNP.zip)

The command I used to perform this analysis is:
Segmentum calculate BAF /reference/fasta/hg38.fa tumor_sample_SNP.tsv tumor_sample_1a.sorted.markdup.BQSR.bam normal.sorted.markdup.BQSR.bam --hetz=4:0.3 -q20 | gzip -c > tumor_B_allele_fraction.tsv.gz

**Comment by eafyounian** [comment] 2024-03-27 07:41
Can you please check if this file ([tumor_sample_SNP.zip](https://github.com/eafyounian/Segmentum/files/14769637/tumor_sample_SNP.zip)) works?
This is the first few lines of the file you shared. What I have done is to replace the `\r\n` with `\n` (to change from MS Windows to Unix format).

May I ask if you had prepared the `tumor_sample_SNP.tsv` file in MS Windows and whether you are running any of these commands on MS Windows? `Segmentum` was made for Unix-like systems and it may not work on machines running on MS Windows.

**Comment by DeMagicscience** [comment] 2024-03-27 08:47
Yes, I prepared the tumor_sample_SNP.tsv file by R installed in windows.
I have used the command in Linux environment: 
$ dos2unix tumor_SNP.tsv
dos2unix: converting file tumor_SNP.tsv to Unix format ...
[tumor_SNP.zip](https://github.com/eafyounian/Segmentum/files/14770435/tumor_SNP.zip)

but the abovementioned error still appeared:
Pre-filtering variants with less than 4 alt reads...
Ignoring reads with MAPQ below 20...
[bed_read] Parse error reading tumor_SNP_test.tsv at line 1
samtools mpileup: Could not read file "tumor_SNP_test.tsv": Success

Do you have a SNP position file for hg38? 
I cannot download this file from the following link. The message is:
Forbidden
You don't have permission to access this resource.
(Note on SNP postion file: You can either use the provided SNP postion file or make one of your own. If you are planning to use the provided one you can download it from here: http://compbio.uta.fi/segmentum/hg19_1000g_2014oct_SNPs.tsv.gz.)

**Comment by eafyounian** [comment] 2024-03-27 09:56
Can you please run this command on the command line and if you are receiving an error?

```bash
samtools mpileup -l tumor_SNP_test.tsv -f /reference/fasta/hg38.fa tumor_sample_1a.sorted.markdup.BQSR.bam normal.sorted.markdup.BQSR.bam
```

>Do you have a SNP position file for hg38?

Unfortunately, no!

>I cannot download this file from the following link.

Thank you for pointing this out, I will try to fix the issue with the dead link in the next couple of days.

**Comment by DeMagicscience** [comment] 2024-03-27 10:58
> samtools mpileup -l tumor_SNP_test.tsv -f /reference/fasta/hg38.fa tumor_sample_1a.sorted.markdup.BQSR.bam normal.sorted.markdup.BQSR.bam

The same error still exists in the log file:
[bed_read] Parse error reading "tumor_SNP_test.tsv" at line 1
samtools mpileup: Could not read file "tumor_SNP_test.tsv"

So, it seems that the format of my SNP position file is incorrect, thus cannot be read by samtools.
Could you please send me a copy of SNP position file for hg19, either here or to my Email (made08@mails.ucas.edu.cn). So I can carefully check the format difference between them.
Thank you very much!

**Comment by eafyounian** [comment] 2024-03-27 11:21
Thank you for checking!

[Here](https://github.com/eafyounian/Segmentum/files/14772375/hg19_1000g_2014oct_SNPs_head.tsv.gz) is the `head` of the requested file as the original file is that big that cannot be attached here or to an email. Although, I doubt that this is an issue due to the file format, let's check this to be sure.

This could also be a `samtools` version issue. Which `samtools` version are you using? Is it possible for you to make a Python environment and install `samtools` version `1.1` and run the above command with this version and see if the issue is resolved?

Thank you in advance for checking! :)

**Comment by DeMagicscience** [comment] 2024-03-28 03:16
> This could also be a `samtools` version issue. Which `samtools` version are you using? Is it possible for you to make a Python environment and install `samtools` version `1.1` and run the above command with this version and see if the issue is resolved?

I used samtools v1.19.1. As you suggested, I installed samtools version 1.1 in an independent conda environment, but it gave exactly the same error message.

I also check the format of the SNP position file.  It seems no difference.
I have no idea how to solve this problem. So, I performed Segmentum analyze without BAF with command:
Segmentum analyze without BAF sample_x_t.wig.gz sample_x_n.wig.gz 11 0.7

the error message in log file is:
Estimated systematic bias: 0.195.
minimum number of reads required at each location to calculate the coverage log ratio: 50.
The following window_sizes were estimated: 11, 241, 17, 241, 27, 241, 41, 241, 63, 241, 95, 241, 143, 241, 215, 241, 
The following thresholds were estimated for log ratios track: 0.7, 0.15, 0.57, 0.15, 0.47, 0.15, 0.38, 0.15, 0.31, 0.15, 0.25, 0.15, 0.21, 0.15, 0.17, 0.15, 
/public/Segmentum-master/bin/Segmentum:587: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  mask = np.zeros(len(logr), dtype = np.bool)
Traceback (most recent call last):
  File "/public/Segmentum-master/bin/Segmentum", line 965, in <module>
    segmentum_without_baf(int(args['--min_read']), args['<tumor>'], args['<normal>'], int(args['<window_size>']),  float(args['<clogr_threshold>']), float(args['--logr_merge']), 5, args['--print'])
  File "/public/Segmentum-master/bin/Segmentum", line 943, in segmentum_without_baf
    change_points_list = [find_consensus_only_for_logr_win_wise(filtered_log_ratios, win_sizes[i], logr_thresholds[i]) for i in range(0, len(win_sizes))]
  File "/public/Segmentum-master/bin/Segmentum", line 943, in <listcomp>
    change_points_list = [find_consensus_only_for_logr_win_wise(filtered_log_ratios, win_sizes[i], logr_thresholds[i]) for i in range(0, len(win_sizes))]
  File "/public/Segmentum-master/bin/Segmentum", line 587, in find_consensus_only_for_logr_win_wise
    mask = np.zeros(len(logr), dtype = np.bool)
  File "/public/miniconda3/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by eafyounian** [comment] 2024-03-28 08:28
Hello! Thank you for the info. I will try to figure out/fix both issues. Hopefully, soon! :)

**Comment by DeMagicscience** [comment] 2024-03-28 08:51
Thank you for your help!

**Comment by eafyounian** [comment] 2024-03-28 12:08
I updated the [Segmentum.py](https://github.com/eafyounian/Segmentum/blob/master/Segmentum.py) file to fix the issue. Can you please check if it works now for you without error?

Essentially, it should be enough to download the latest version of `Segmentum.py` and replace the older file with it.

I will look into the `samtools issue` soon.

**Comment by eafyounian** [comment] 2024-03-28 13:05
I think the issue with `samtools` can be fixed by removing the **header line** from your SNP position file. I will update the "Example" section so that it is less confusing. 

```
chr	position
```

Can you please check let me know if both issues are now fixed? Thank you in advance! :)

**Comment by eafyounian** [comment] 2024-03-29 19:14
The broken links are now also fixed on the README page! :)

**Comment by DeMagicscience** [comment] 2024-04-01 09:13
> I updated the [Segmentum.py](https://github.com/eafyounian/Segmentum/blob/master/Segmentum.py) file to fix the issue. Can you please check if it works now for you without error?
> 
> Essentially, it should be enough to download the latest version of `Segmentum.py` and replace the older file with it.
> 
> I will look into the `samtools issue` soon.

Yes, it works.

**Comment by DeMagicscience** [comment] 2024-04-01 09:22
> I think the issue with `samtools` can be fixed by removing the **header line** from your SNP position file. I will update the "Example" section so that it is less confusing.
> 
> ```
> chr	position
> ```
> 
> Can you please check let me know if both issues are now fixed? Thank you in advance! :)

Now, I can get a log file without error information. 
[BAF_tumor_sample.e26188102.txt](https://github.com/eafyounian/Segmentum/files/14821945/BAF_tumor_sample.e26188102.txt)

However, the output of BAF is empty except the header.
[tumor_sample_B_allele_fraction.tsv.txt](https://github.com/eafyounian/Segmentum/files/14821961/tumor_sample_B_allele_fraction.tsv.txt)

**Comment by eafyounian** [comment] 2024-04-01 11:26
>However, the output of BAF is empty except the header.
🤔 I will look into this. In the meantime, will you please check e.g., whether the chromosome names in your BAM file is similar to your SNP file (e.g., both '1' or both 'chr1')? If they are different, it may be easier to modify the SNP file to be compatible with the BAM files.

**Comment by DeMagicscience** [comment] 2024-04-02 02:56
> > However, the output of BAF is empty except the header.
> > 🤔 I will look into this. In the meantime, will you please check e.g., whether the chromosome names in your BAM file is similar to your SNP file (e.g., both '1' or both 'chr1')? If they are different, it may be easier to modify the SNP file to be compatible with the BAM files.

Problem solved! Thank you for your patient answer.

**Comment by eafyounian** [comment] 2024-04-02 08:16
Glad to here that! :) May I ask, how did you manage to solved the latest issue? Thank you in advance! :)

**Comment by DeMagicscience** [comment] 2024-04-02 08:42
> Glad to here that! :) May I ask, how did you manage to solved the latest issue? Thank you in advance! :)

As you suggested, change the chromosome names of BAM file and SNP file to be the same.
Sorry for not making it clear.
Thank you!

**Comment by eafyounian** [comment] 2024-04-02 18:21
Great! Thank you for the elaboration! Glad to hear that the issue is now resolved! :)

**Comment by eafyounian** [comment] 2024-05-10 11:00
The issue(s) raised have been now addressed.

**Comment by eafyounian** [comment] 2024-05-10 11:01
The issue(s) raised here have now been addressed.

**Closed as completed by eafyounian** 2024-05-10 11:01 UTC
